title: Abhishek Shirgaokar
author: Abhishek Shirgaokar
email: abhishek.shirgaokar at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Hey! Welcome to Abhishek Shirgaokar's blog. Find explained implementations of many cutting edge deep learning techniques here alongside 
  other artifical intelligence & machine learning (ML) posts. Computer Vision, Natural Langauge Processing, 
  Linux scripts, Data Science workflows and more.....

url: "ashirgao.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  ashirgao
comments: true
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
theme: jekyll-theme-minimal
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
