title: ashirgao.github.io
author: Abhishek Shirgaokar
email: abhishek.shirgaokar at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Hey! I'm using this site to document some of my interesting learnings. If you 
  have landed on this page looking for something, I hope you find it. Contact me in case of any corrections or if you have an interesting 
  project idea you'd like to collaborate on.

url: "ashirgao.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  ashirgao
comments: true
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
theme: jekyll-theme-minimal
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
